batch_size: 1
epochs: 30
epochs_til_checkpoint: 5
eval_split: split/eval/50020.txt
checkpoint_path: 'models/50020_train/model_current.pth'
experiment_name: 50020_eval
hidden_num: 128
latent_dim: 128
part_num: 20
hyper_hidden_layers: 2
hyper_hidden_features: 256
logging_root: ./eval
lr: 0.0001
max_points: 200000
model_type: sine
num_instances: 2084
on_surface_points: 4000
point_cloud_path: ../../dataset/D-FAUST/wo_scale/registrations_f/50020_chicken_wings/surface_pts_n_normal
steps_til_summary: 100
