batch_size: 1
epochs: 30
epochs_til_checkpoint: 5
eval_split: split/eval/50026.txt
#checkpoint_path: 'models/50026_train/model_current.pth'
checkpoint_path: 'logs/50026_train/checkpoints/model_current.pth'
experiment_name: 50026_eval3
hidden_num: 128
latent_dim: 128
part_num: 20
hyper_hidden_layers: 2
hyper_hidden_features: 256
logging_root: ./eval
lr: 0.0001
max_points: 200000
model_type: sine
num_instances: 4350
on_surface_points: 4000
point_cloud_path: ../../dataset/D-FAUST/wo_scale/registrations_m/50026_shake_arms/surface_pts_n_normal
steps_til_summary: 100
