batch_size: 1
epochs: 30
epochs_til_checkpoint: 5
eval_split: split/eval/bear3EP.txt
checkpoint_path: models/bear3EP/model_final.pth
experiment_name: bear3EP_eval_partial
expand: -1
hidden_num: 128
latent_dim: 128
part_num: 20
hyper_hidden_layers: 3
hyper_hidden_features: 256
logging_root: ./eval
lr: 0.001
max_points: 500000
model_type: sine
num_instances: 2283
on_surface_points: 4000
point_cloud_path: data/test_data/bear3EP/partial_points
steps_til_summary: 100
eval_corr_split: split/eval/bear3EP_test_100.txt
mesh_path: data/test_data/bear3EP/mesh
geo_mesh_path: data/test_data/bear3EP/mesh_for_geodesic_distance
geodesic_distance_path: data/test_data/bear3EP/distance_matrix