batch_size: 1
epochs: 30
epochs_til_checkpoint: 5
eval_split: split/eval/deer2MB.txt
checkpoint_path: models/deer2MB/model_final.pth
experiment_name: deer2MB_eval_partial
expand: 0.01
hidden_num: 128
latent_dim: 128
part_num: 20
hyper_hidden_layers: 3
hyper_hidden_features: 256
logging_root: ./eval
lr: 0.001
max_points: 500000
model_type: sine
num_instances: 861
on_surface_points: 4000
point_cloud_path: data/test_data/deer2MB/partial_points
steps_til_summary: 100
eval_corr_split: split/eval/deer2MB_test_100.txt
mesh_path: data/test_data/deer2MB/mesh
geo_mesh_path: data/test_data/deer2MB/mesh_for_geodesic_distance
geodesic_distance_path: data/test_data/deer2MB/distance_matrix