batch_size: 64
epochs: 60
epochs_til_checkpoint: 5
expand: -1
experiment_name: bear3EP_finetune
hidden_num: 128
latent_dim: 128
hyper_hidden_layers: 3
part_num: 20
logging_root: ./logs
loss_correct: 100.0
loss_grad_deform: 2
loss_grad_temp: 400.0
lr: 0.0001
max_points: 200000
model_type: sine
on_surface_points: 4000
point_cloud_root: ../../dataset/DeformingThings4D/animals_sdf_scale
steps_til_summary: 1000
train_split_root: split/train
subject_group_id: [bear3EP]
epochs_til_full_loss: 10
checkpoint_path: 'logs/bear3EP/checkpoints/model_final.pth'
