experiment_name: '50004_train_sal'
checkpoint_path: 'logs/50004_train_finetune/checkpoints/model_current.pth'
num_instances: 672
latent_dim: 128
part_num: 20
model_type: 'sine'
hidden_num: 128
hyper_hidden_layers: 3
hyper_hidden_features: 256