experiment_name: '50022_train'
checkpoint_path: 'logs/50022_train_sal/checkpoints/model_current.pth'
num_instances: 710
latent_dim: 128
part_num: 20
model_type: 'sine'
hidden_num: 128
hyper_hidden_layers: 3
hyper_hidden_features: 256
