experiment_name: bunnyQ
checkpoint_path: 'logs/bunnyQ/checkpoints/model_epoch_0050.pth'
num_instances: 1323
latent_dim: 128
part_num: 20
model_type: 'sine'
hidden_num: 128
hyper_hidden_layers: 3
hyper_hidden_features: 256