experiment_name: 'cloth'
checkpoint_path: 'logs/cloth/checkpoints/model_current.pth'
num_instances: 100
latent_dim: 128
model_type: 'sine'
hidden_num: 128
hyper_hidden_layers: 1
hyper_hidden_features: 256
