experiment_name: pumaRW
checkpoint_path: 'logs/pumaRW/checkpoints/model_current.pth'
num_instances: 3087
latent_dim: 128
part_num: 20
model_type: 'sine'
hidden_num: 128
hyper_hidden_layers: 3
hyper_hidden_features: 256