experiment_name: raccoonVGG
checkpoint_path: 'logs/raccoonVGG/checkpoints/model_current.pth'
num_instances: 2238
latent_dim: 128
part_num: 20
model_type: 'sine'
hidden_num: 128
hyper_hidden_layers: 3
hyper_hidden_features: 256