experiment_name: 'wings'
checkpoint_path: 'logs/wings/checkpoints/model_current.pth'
num_instances: 226
latent_dim: 128
part_num: 20
rank: 3
model_type: 'sine'
hidden_num: 128
hyper_hidden_layers: 1
hyper_hidden_features: 256
