batch_size: 80
epochs: 200
epochs_til_checkpoint: 5
expand: -1
experiment_name: 50022_train2
hidden_num: 128
latent_dim: 128
hyper_hidden_layers: 3
part_num: 20
logging_root: ./logs
loss_correct: 100.0
loss_grad_deform: 2
loss_grad_temp: 400.0
lr: 0.0001
max_points: 200000
model_type: sine
on_surface_points: 4000
point_cloud_root: ../../dataset/D-FAUST/with_scale/registrations_f
train_split_root: split/train_sal
subject_group_id: [50022]
steps_til_summary: 1000
epochs_til_full_loss: 10