batch_size: 32
epochs: 100
epochs_til_checkpoint: 5
expand: -1
experiment_name: male_train
hidden_num: 128
latent_dim: 128
hyper_hidden_layers: 2
part_num: 20
logging_root: ./logs
loss_correct: 100.0
loss_grad_deform: 2
loss_grad_temp: 400.0
lr: 0.0001
max_points: 200000
model_type: sine
on_surface_points: 4000
point_cloud_root: ../../dataset/D-FAUST/wo_scale/registrations_m
train_split_root: split/train_sal
subject_group_id: [50002,50007,50009,50026,50027]
steps_til_summary: 1000
