batch_size: 256
epochs: 70
epochs_til_checkpoint: 5
expand: 0.005
experiment_name: shake_hips
hidden_num: 128
latent_dim: 128
part_num: 20
rank: 5
logging_root: ./logs
loss_correct: 100.0
loss_grad_deform: 2
loss_grad_temp: 200.0
lr: 0.0001
max_points: 200000
model_type: sine
num_instances: 214
on_surface_points: 800
point_cloud_path: /media/sdb/dataset/D-FAUST/registration_f/50004_shake_hips/surface_pts_n_normal
steps_til_summary: 100
train_split: split/train/shake_hips.txt
