batch_size: 16
epochs: 140
epochs_til_checkpoint: 5
expand: 0.001
experiment_name: wings
hidden_num: 128
latent_dim: 128
hyper_hidden_layers: 1
part_num: 20
rank: 3
num_point_freqs: 0
logging_root: ./logs
loss_correct: 100.0
loss_grad_deform: 2
loss_grad_temp: 400.0
lr: 0.001
stage2_start_step: 1000000
max_points: 1000000
hann_width: 20000
model_type: sine
num_instances: 226
on_surface_points: 4000
point_cloud_path: ../../dataset/D-FAUST/w_surface/registrations_f/50004_chicken_wings/surface_pts_n_normal
steps_til_summary: 1000
train_split: split/train/wings.txt
