eval_split: split/train/50025.txt
checkpoint_path: 'models/50025/model_final.pth'
expand: -1
experiment_name: 50025_train
hidden_num: 128
latent_dim: 128
part_num: 20
hyper_hidden_layers: 3
hyper_hidden_features: 256
logging_root: ./eval
model_type: sine
num_instances: 724
point_cloud_path: data/train_data/50025/surface_pts_n_normal
eval_corr_split: split/train/50025_train_100.txt
mesh_path: data/train_data/50025/mesh
geo_mesh_path: data/train_data/50025/mesh_for_geodesic_distance
geodesic_distance_path: data/train_data/50025/distance_matrix