batch_size: 80
epochs: 200
epochs_til_checkpoint: 5
expand: -1
experiment_name: 50002_train
hidden_num: 128
latent_dim: 128
hyper_hidden_layers: 3
part_num: 20
logging_root: ./logs
lr: 0.0001
max_points: 200000
model_type: sine
on_surface_points: 4000
point_cloud_root: ../../dataset/D-FAUST/with_scale/registrations_m
train_split_root: split/train
subject_group_id: [50002]
steps_til_summary: 1000