batch_size: 32
epochs: 15
epochs_til_checkpoint: 5
expand: -1
experiment_name: 50027_train
hidden_num: 128
latent_dim: 128
hyper_hidden_layers: 2
part_num: 20
logging_root: ./logs
loss_correct: 100.0
loss_grad_deform: 2
loss_grad_temp: 400.0
lr: 0.0001
max_points: 200000
model_type: sine
on_surface_points: 4000
point_cloud_path: ../../dataset/D-FAUST/wo_scale/registrations_m/50027_train/surface_pts_n_normal
steps_til_summary: 1000
train_split: split/train/50027.txt
num_instances: 3529
