batch_size: 8
epochs: 15
epochs_til_checkpoint: 5
expand: -1
experiment_name: wings_stage2
hidden_num: 128
latent_dim: 128
hyper_hidden_layers: 2
part_num: 10
rank: 3
num_point_freqs: 0
logging_root: ./logs
loss_correct: 100.0
loss_grad_deform: 2
loss_grad_temp: 400.0
lr: 0.0001
max_points: 500000
model_type: sine
on_surface_points: 4000
point_cloud_path: ../../dataset/D-FAUST/wo_scale/registrations_f/50004_chicken_wings/surface_pts_n_normal
steps_til_summary: 1000
train_split: split/train/wings.txt
num_instances: 226
