batch_size: 24
epochs: 70
epochs_til_checkpoint: 5
expand: 0.001
experiment_name: wings
hidden_num: 128
latent_dim: 128
part_num: 20
rank: 3
logging_root: ./logs
loss_correct: 200.0
loss_grad_deform: 2
loss_grad_temp: 400.0
lr: 0.00001
max_points: 200000
model_type: sine
num_instances: 226
on_surface_points: 1000
point_cloud_path: ../../dataset/D-FAUST/wo_scale/registrations_f/50004_chicken_wings/surface_pts_n_normal
steps_til_summary: 100
train_split: split/train/wings.txt
